# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
      
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Spring boot 앱을 빌드해서 DockerHub에 push하는 job
  build-docker-image-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    
    steps:
    # Github 레포지토리로부터 CI서버로 소스코드를 내려받은 후에 지정한 브랜치로 전환하는 역할
    - name: Checkout
      uses: actions/checkout@v3

    # env 셋업 
    # The branch or tag ref that triggered the workflow. For example, refs/heads/feature-branch-1. If neither a branch or tag is available for the event type, the variable will not exist.
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    # Java 17 버전 세팅
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # 빌드를 위한 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # Gradle을 이용하여 빌드
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean bootJar

    # docker buildx 셋업
    - name: Set up Docker buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    # DockerHub 로그인
    # CR_PAT: Container Registry Personal Acccess Token
    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}        
        password: ${{ secrets.CR_PAT }}
    
    # Docker 이미지 빌드 및 DockerHub에 push
    - name: Build and Push
      uses: docker/build-push-action@v5
      id: docker_build
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/github-actions-practice:latest
          ghcr.io/${{ github.repository_owner }}/github-actions-practice:${{ env.RELEASE_VERSION }}
    
    # docker_build 로깅
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
